name: Build/N1

on: 
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/build-N1.yml'
  schedule:
    - cron: '40 10 1-31/7 * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone --mirror --no-single-branch --depth=$DEPTH $SRC_REPO repo.git
        env:
          SRC_REPO: https://github.com/tuanqing/mknop.git
          DEPTH: 1
      - name: Config DownStream
        run: git -C repo.git remote add downstream "$PUSH_TARGET"
        env:
          PUSH_TARGET: https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USER }}/N1build
      - name: Push Downstream Or Try Unshallow On Failed
        run: |
          git -C repo.git fetch --unshallow origin || exit 1 
          git -C repo.git gc
          git -C repo.git count-objects -vH
          git -C repo.git push --all --force downstream && git -C repo.git push --tags downstream
